blank_issues_enabled: false
contact_links:
  - name: â“ General Questions / Discussions
    url: https://github.com/MartinZikmund/content-suggestions/discussions
    about: Use GitHub Discussions for questions or open-ended brainstorming.
